require('json2ify')
require('es5-shimify')
require('jqueryify')

require('spine')
require('spine/lib/local')
require('spine/lib/manager')
require('spine/lib/route')

require("lib/chart/highchart")
require("lib/bootstrap.min")
require("lib/bootstrap-editable")
require("lib/jquery.serializeObject")
require("lib/bootstrap-datetimepicker")
require("lib/bootstrap-datetimepicker.zh-CN")
require("lib/selectize")
